### ISSUE TITLE
How to use emojify with espanso

### ISSUE THREAD

**Issue by HaleTom** [mrowa44/emojify#58]
[Espanso](https://espanso.org/) expands text typed from the keyboard, and works great with emojify.

eg, I can type `:heart:` anywhere, and it is replaced with `❤️`.

```
matches:
  # Emojify emoji expansion :emoji:
  - regex: /:(?P<emojiName>[^:\s]+):/
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: emojify "{{emojiName}}"
```

Is there a wiki or KB that this could go into?
